---
AWSTemplateFormatVersion: "2010-09-09"
Description: Website Cloudformation Template

Parameters:
  TagsStackName:
    Description: Tags Stack Name
    Type: String
  VpcStackName:
    Description: VPC Stack Name
    Type: String
  LaunchTemplateStackName:
    Description: Launch Template Stack Name
    Type: String

  NumberSubnets:
    Description: Number of Subnets
    Type: Number
    Default: 2
    MinValue: 2
    MaxValue: 6
  GroupMinSize:
    Description: Minimum number of servers in autoscaling group
    Type: Number
    Default: 1
  GroupMaxSize:
    Description: Maximum number of servers in autoscaling group
    Type: Number
    Default: 4

Conditions:
  UseSubnet2: !Or
    - !Equals [ !Ref NumberSubnets, 3 ]
    - !Equals [ !Ref NumberSubnets, 4 ]
    - !Equals [ !Ref NumberSubnets, 5 ]
    - !Equals [ !Ref NumberSubnets, 6 ]
  UseSubnet3: !Or
    - !Equals [ !Ref NumberSubnets, 4 ]
    - !Equals [ !Ref NumberSubnets, 5 ]
    - !Equals [ !Ref NumberSubnets, 6 ]
  UseSubnet4: !Or
    - !Equals [ !Ref NumberSubnets, 5 ]
    - !Equals [ !Ref NumberSubnets, 6 ]
  UseSubnet5: !Equals [ !Ref NumberSubnets, 6 ]

Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Join
        - '-'
        - - !Ref AWS::StackName
          - tg
      VpcId: !ImportValue
        'Fn::Sub': ${VpcStackName}-VpcId
      Port: 80
      Protocol: HTTP
      Tags:
        - Key: Project
          Value: !ImportValue
              'Fn::Sub': ${TagsStackName}-ProjectName
        - Key: Environment
          Value: !ImportValue
              'Fn::Sub': ${TagsStackName}-Environment

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !ImportValue
            'Fn::Sub': ${LaunchTemplateStackName}-LaunchTemplate
        Version: !ImportValue
            'Fn::Sub': ${LaunchTemplateStackName}-Version
      MinSize: !Ref GroupMinSize
      MaxSize: !Ref GroupMaxSize
      TargetGroupARNs:
        - !Ref TargetGroup
      VPCZoneIdentifier:
        - !ImportValue
          'Fn::Sub': ${VpcStackName}-PrivateSubnet0
        - !ImportValue
          'Fn::Sub': ${VpcStackName}-PrivateSubnet1
        - !If
          - UseSubnet2
          - !ImportValue
            'Fn::Sub': ${VpcStackName}-PrivateSubnet2
          - !Ref AWS::NoValue
        - !If
          - UseSubnet3
          - !ImportValue
            'Fn::Sub': ${VpcStackName}-PrivateSubnet3
          - !Ref AWS::NoValue
        - !If
          - UseSubnet4
          - !ImportValue
            'Fn::Sub': ${VpcStackName}-PrivateSubnet4
          - !Ref AWS::NoValue
        - !If
          - UseSubnet5
          - !ImportValue
            'Fn::Sub': ${VpcStackName}-PrivateSubnet5
          - !Ref AWS::NoValue
      Tags:
        - Key: Project
          Value: !ImportValue
              'Fn::Sub': ${TagsStackName}-ProjectName
          PropagateAtLaunch: True
        - Key: Environment
          Value: !ImportValue
              'Fn::Sub': ${TagsStackName}-Environment
          PropagateAtLaunch: True
#    CreationPolicy:
#      ResourceSignal:
#        Timeout: PT15M
#        Count: 1
#    UpdatePolicy:
#      AutoScalingRollingUpdate:
#        MinInstancesInService: !Ref GroupMinSize
#        MaxBatchSize: 1
#        PauseTime: PT15M
#        WaitOnResourceSignals: true

Outputs:
  TargetGroupARN:
    Description: Target Group ARN
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${AWS::StackName}-TargetGroupArn
